fix: Add T12 template to TemplatePreviewModal component
Added Template12 import and registration to TemplatePreviewModal:
- Import Template12 from @/templates/t12
- Added t12 to templateComponents object

This fixes the TypeScript error:
'Property t12 does not exist on type { t6: ..., t7: ..., t9: ..., t10: ..., t11: ... }'

Now T12 (Aviator Crash) template can be previewed in the template selection modal